### ISSUE TITLE
您好 我在windows上进行编译时遇到了一些小小的问题

### ISSUE THREAD

**Issue by chaojibendan** [iiicp/lcc#3]
我按照mysy下载了相应包以及添加了环境变量
![cbadd7f360bf9843d454db2d73f25a1](https://user-images.githubusercontent.com/112836831/218121290-15e989ed-cd93-4141-b116-06929cdbd7d7.png)
![fe6db122803cf267622bc99edf04209](https://user-images.githubusercontent.com/112836831/218121337-02f3423c-51ff-43f9-a905-40177d2c37ad.png)
![d1cbd499614048143f02f9c56d50863](https://user-images.githubusercontent.com/112836831/218121379-c29e8c5e-e940-4b22-8ee0-e8d02568c675.png)
可是却没有编译成功，出现了多处问题以及note提醒，主要有
![f0464ab12bed198251f66df01b9365e](https://user-images.githubusercontent.com/112836831/218121579-b406367f-4ce6-416f-822b-79dba2c152e3.png)
![efc208ff0e685bfccbd5866738d8182](https://user-images.githubusercontent.com/112836831/218121607-623c3524-deab-4477-a738-cc274529
![023f5dd3e8940174efa42034b2d4dc2](https://user-images.githubusercontent.com/112836831/218121619-feb3b477-a247-4778-886d-8c71aebcfa42.png)
62df.png)
我发现主要与c++的头文件有关，想请问是因为版本不同出现的问题还是我自己有某处操作不当？

**Comment by chaojibendan** [comment]
![efc208ff0e685bfccbd5866738d8182](https://user-images.githubusercontent.com/112836831/218123840-eded0129-d2dd-4205-92f3-99af029dfb65.png)

**Comment by iiicp** [comment]
done
